#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <assert.h>

#include "com_timmattison_sjmmie_SjmmieLibrary.h"   // Generated by javah

static JavaVM *jvm;

jobject open_callback_object;

JNIEnv *getJNIEnv() {
	// Assistance from here: http://adamish.com/blog/archives/327
	JNIEnv *g_env;

	int getEnvStat = (*jvm)->GetEnv(jvm, (void **) &g_env, JNI_VERSION_1_6);

	if (getEnvStat == JNI_EDETACHED) {
		printf("GetEnv: not attached\n");
		if ((*jvm)->AttachCurrentThread(jvm, (void **) &g_env, NULL) != 0) {
			printf("Failed to attach\n");
		}
	} else if (getEnvStat == JNI_OK) {
	} else if (getEnvStat == JNI_EVERSION) {
		printf("GetEnv: version not supported\n");
	}

	return g_env;
}

/*
void detach_from_thread() {
	(*jvm)->DetachCurrentThread(jvm);
}
*/

void get_jvm_reference(JNIEnv *env) {
	// Do we already have a reference to the JVM?
	if(jvm != NULL) {
		// Yes, just return
		return;
	}

	// Get a reference to the JVM
	jint rs = (*env)->GetJavaVM(env, &jvm);

	// Make sure that JNI says that the method returned properly
	assert (rs == JNI_OK);
}

JNIEXPORT void JNICALL Java_com_timmattison_sjmmie_SjmmieLibrary_callFromJava(JNIEnv *env, jobject obj) 
{
	printf("JNI: Called from Java\n");
}

JNIEXPORT void JNICALL Java_com_timmattison_sjmmie_SjmmieLibrary_setOpenCallback(JNIEnv *env, jobject obj, jobject callbackObject)
{
	// From http://stackoverflow.com/questions/12420463/jni-keeping-global-reference-to-the-environment
	// Get a reference to the JVM, if necessary
	get_jvm_reference(env);

	open_callback_object = (*env)->NewGlobalRef(env, callbackObject);
}

JNIEXPORT void JNICALL Java_com_timmattison_sjmmie_SjmmieLibrary_clearOpenCallback(JNIEnv *env, jobject obj)
{
	if(open_callback_object == NULL) {
		return;
	}

	(*env)->DeleteGlobalRef(env, open_callback_object);
}

int inner_original_open(const char *filename, int flags) {
	int (*original_open)(const char*, int);
	original_open = dlsym(RTLD_NEXT, "open");
	return (*original_open)(filename, flags);
}

JNIEXPORT int JNICALL Java_com_timmattison_sjmmie_SjmmieLibrary_originalOpen(JNIEnv *env, jobject obj, jstring filename, jint flags) {
	int return_value;

	// Convert the string to a const char *
	const char *c_filename = (*env)->GetStringUTFChars(env, filename, NULL);
	printf("FINAL FILENAME: %s\n", c_filename);

	// Call the original function and store the result
	return_value = inner_original_open(c_filename, flags);

	// Release the resources for the converted string
	(*env)->ReleaseStringUTFChars(env, filename, c_filename);

/*
	// Detach the JVM from this thread
	detach_from_thread();
*/

	// Return the result
	return return_value;
}

int open(const char *filename, int flags, ...) {
	printf("OPEN, opening %s [%d]\n", filename, flags);

	if(open_callback_object != NULL) {
		jmethodID java_open_method;
		jclass open_callback_class;

		printf("OPEN callback to Java 1\n");
		JNIEnv *env = getJNIEnv();
		printf("OPEN callback to Java 2\n");

		open_callback_class = (*env)->GetObjectClass(env, open_callback_object);
		printf("OPEN callback to Java 3\n");

		java_open_method = (*env)->GetMethodID(env, open_callback_class, "callback", "(Ljava/lang/String;I)I");
		printf("OPEN callback to Java 4\n");
		jint return_value = (*env)->CallIntMethod(env, open_callback_object, java_open_method, (*env)->NewStringUTF(env, filename), flags);
		printf("OPEN callback to Java 5\n");
	
		return return_value;
	}
	else {
		printf("OPEN no callback\n");
		return inner_original_open(filename, flags);
	}
}
